### ISSUE TITLE
Cheatsheet of functions in Distance?

### ISSUE THREAD

**Issue by dill** [dill/distance-package-paper#31]
Things like `AIC`, `plot`, `summarize_ds_models` etc.

**Comment by erex** [comment]
Would this be another appendix (or did the comparison with other packages idea go away?)?  Or rather would it be Table 4?  I don't expect the table would details the arguments for said functions, so what would the table contain other than a list of function names (because the names are pretty self-explanatory).

**Comment by dill** [comment]
@erex [Appendix A](https://github.com/dill/distance-package-paper/blob/master/Appendix-A-Comparison.md) has the comparison.

I think I agree, I don't think this is actually this useful, especially if there are worked examples in the paper.
